In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# DATA **INTERPRETATION**



In [ ]:
train_path = '/content/drive/My Drive/Food_Demand_Forecast_Project/updated_train.csv'
test_path = '/content/drive/My Drive/Food_Demand_Forecast_Project/updated_test.csv'

In [ ]:
train_df = pd.read_csv(train_path) 
test_df = pd.read_csv(test_path)

In [ ]:
train_df.shape

(456548, 16)

In [ ]:
test_df.shape

(32573, 15)

In [ ]:
train_df.head()

Unnamed: 0       id  week  center_id  ...  center_type  op_area   category  cuisine
0           0  1379560     1         55  ...       TYPE_C      2.0  Beverages     Thai
1           1  1018704     2         55  ...       TYPE_C      2.0  Beverages     Thai
2           2  1196273     3         55  ...       TYPE_C      2.0  Beverages     Thai
3           3  1116527     4         55  ...       TYPE_C      2.0  Beverages     Thai
4           4  1343872     5         55  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 16 columns]

In [ ]:
train_df.category.unique().shape

(14,)

In [ ]:
train_df.category.unique()

array(['Beverages', 'Rice Bowl', 'Starters', 'Pasta', 'Sandwich',
       'Biryani', 'Extras', 'Pizza', 'Seafood', 'Other Snacks', 'Desert',
       'Salad', 'Fish', 'Soup'], dtype=object)

In [ ]:
train_df.cuisine.unique()

array(['Thai', 'Indian', 'Italian', 'Continental'], dtype=object)

In [ ]:
train_df.center_type.unique()

array(['TYPE_C', 'TYPE_B', 'TYPE_A'], dtype=object)

In [ ]:
test_df.head()

Unnamed: 0       id  week  center_id  ...  center_type  op_area   category  cuisine
0           0  1028232   146         55  ...       TYPE_C      2.0  Beverages     Thai
1           1  1262649   147         55  ...       TYPE_C      2.0  Beverages     Thai
2           2  1453211   149         55  ...       TYPE_C      2.0  Beverages     Thai
3           3  1262599   150         55  ...       TYPE_C      2.0  Beverages     Thai
4           4  1495848   151         55  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 15 columns]

In [ ]:
train_df.drop(['Unnamed: 0'],axis=1,inplace=True)
train_df.head()

id  week  center_id  meal_id  ...  center_type  op_area   category  cuisine
0  1379560     1         55     1885  ...       TYPE_C      2.0  Beverages     Thai
1  1018704     2         55     1885  ...       TYPE_C      2.0  Beverages     Thai
2  1196273     3         55     1885  ...       TYPE_C      2.0  Beverages     Thai
3  1116527     4         55     1885  ...       TYPE_C      2.0  Beverages     Thai
4  1343872     5         55     1885  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 15 columns]

In [ ]:
test_df.drop(['Unnamed: 0'],axis=1,inplace=True)
test_df.head()

id  week  center_id  meal_id  ...  center_type  op_area   category  cuisine
0  1028232   146         55     1885  ...       TYPE_C      2.0  Beverages     Thai
1  1262649   147         55     1885  ...       TYPE_C      2.0  Beverages     Thai
2  1453211   149         55     1885  ...       TYPE_C      2.0  Beverages     Thai
3  1262599   150         55     1885  ...       TYPE_C      2.0  Beverages     Thai
4  1495848   151         55     1885  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 14 columns]

In [ ]:
test_df.shape

(32573, 14)

In [ ]:
train_df.shape

(456548, 15)

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32573 entries, 0 to 32572
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     32573 non-null  int64  
 1   week                   32573 non-null  int64  
 2   center_id              32573 non-null  int64  
 3   meal_id                32573 non-null  int64  
 4   checkout_price         32573 non-null  float64
 5   base_price             32573 non-null  float64
 6   emailer_for_promotion  32573 non-null  int64  
 7   homepage_featured      32573 non-null  int64  
 8   city_code              32573 non-null  int64  
 9   region_code            32573 non-null  int64  
 10  center_type            32573 non-null  object 
 11  op_area                32573 non-null  float64
 12  category               32573 non-null  object 
 13  cuisine                32573 non-null  object 
dtypes: float64(3), int64(8), object(3)
memory usage: 3.5+ 

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   id                     456548 non-null  int64  
 1   week                   456548 non-null  int64  
 2   center_id              456548 non-null  int64  
 3   meal_id                456548 non-null  int64  
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64  
 7   homepage_featured      456548 non-null  int64  
 8   num_orders             456548 non-null  int64  
 9   city_code              456548 non-null  int64  
 10  region_code            456548 non-null  int64  
 11  center_type            456548 non-null  object 
 12  op_area                456548 non-null  float64
 13  category               456548 non-null  object 
 14  cuisine                456548 non-nu

# STATISTICAL **INFO**

In [ ]:
train_df.describe()

id           week  ...    region_code        op_area
count  4.565480e+05  456548.000000  ...  456548.000000  456548.000000
mean   1.250096e+06      74.768771  ...      56.614566       4.083590
std    1.443548e+05      41.524956  ...      17.641306       1.091686
min    1.000000e+06       1.000000  ...      23.000000       0.900000
25%    1.124999e+06      39.000000  ...      34.000000       3.600000
50%    1.250184e+06      76.000000  ...      56.000000       4.000000
75%    1.375140e+06     111.000000  ...      77.000000       4.500000
max    1.499999e+06     145.000000  ...      93.000000       7.000000

[8 rows x 12 columns]

# CHECKING FOR NULL **VALUES**

In [ ]:
train_df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [ ]:
test_df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

# **LABEL ENCODING**

In [ ]:
train_df.head(7)

id  week  center_id  meal_id  ...  center_type  op_area   category  cuisine
0  1379560     1         55     1885  ...       TYPE_C      2.0  Beverages     Thai
1  1018704     2         55     1885  ...       TYPE_C      2.0  Beverages     Thai
2  1196273     3         55     1885  ...       TYPE_C      2.0  Beverages     Thai
3  1116527     4         55     1885  ...       TYPE_C      2.0  Beverages     Thai
4  1343872     5         55     1885  ...       TYPE_C      2.0  Beverages     Thai
5  1493612     6         55     1885  ...       TYPE_C      2.0  Beverages     Thai
6  1110832     7         55     1885  ...       TYPE_C      2.0  Beverages     Thai

[7 rows x 15 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
train_df["cent_type"] = encoder.fit_transform(train_df["center_type"])
train_df[["center_type", "cent_type"]].head(10)

center_type  cent_type
0      TYPE_C          2
1      TYPE_C          2
2      TYPE_C          2
3      TYPE_C          2
4      TYPE_C          2
5      TYPE_C          2
6      TYPE_C          2
7      TYPE_C          2
8      TYPE_C          2
9      TYPE_C          2

In [ ]:
train_df["cent_type"].unique()

array([2, 1, 0])

In [ ]:
train_df["categories"] = encoder.fit_transform(train_df["category"])
train_df[["category", "categories"]].head(10)

category  categories
0  Beverages           0
1  Beverages           0
2  Beverages           0
3  Beverages           0
4  Beverages           0
5  Beverages           0
6  Beverages           0
7  Beverages           0
8  Beverages           0
9  Beverages           0

In [ ]:
train_df["categories"].unique()

array([ 0,  8, 13,  6, 10,  1,  3,  7, 11,  5,  2,  9,  4, 12])

In [ ]:
train_df["Cuisine"] = encoder.fit_transform(train_df["cuisine"])
train_df[["cuisine", "Cuisine"]].head(10)

cuisine  Cuisine
0    Thai        3
1    Thai        3
2    Thai        3
3    Thai        3
4    Thai        3
5    Thai        3
6    Thai        3
7    Thai        3
8    Thai        3
9    Thai        3

In [ ]:
train_df["Cuisine"].unique()

array([3, 1, 2, 0])

In [ ]:
train_df_enc = train_df.drop(['center_type','category','cuisine'], axis=1)

In [ ]:
train_df_enc.head()

id  week  center_id  meal_id  ...  op_area  cent_type  categories  Cuisine
0  1379560     1         55     1885  ...      2.0          2           0        3
1  1018704     2         55     1885  ...      2.0          2           0        3
2  1196273     3         55     1885  ...      2.0          2           0        3
3  1116527     4         55     1885  ...      2.0          2           0        3
4  1343872     5         55     1885  ...      2.0          2           0        3

[5 rows x 15 columns]

# **FEATURE EXTRACTION**

In [ ]:
x = train_df_enc.drop(['num_orders'],axis=1)

In [ ]:
y = train_df_enc['num_orders']

In [ ]:
add_sub_price=x["checkout_price"]-x["base_price"]

In [ ]:
add_sub_price=add_sub_price.to_frame()
add_sub_price.columns=['change_in_price_during_checkout']

In [ ]:
x=pd.concat([x,add_sub_price],axis=1).drop(["checkout_price"],axis=1)

In [ ]:
features=['city_code','week', 'base_price', 'change_in_price_during_checkout','emailer_for_promotion', 'homepage_featured', 'cent_type', 'op_area', 'categories',
       'Cuisine']

In [ ]:
x = x[features]

In [ ]:
x.head()

city_code  week  base_price  ...  op_area  categories  Cuisine
0        647     1      152.29  ...      2.0           0        3
1        647     2      152.29  ...      2.0           0        3
2        647     3      133.92  ...      2.0           0        3
3        647     4      134.86  ...      2.0           0        3
4        647     5      147.50  ...      2.0           0        3

[5 rows x 10 columns]

# **SCALING THE VALUES**

In [ ]:
def data_scaling(X_data):
    scaler=StandardScaler(with_mean=False)
    scaler.fit(X_data)
    scaled_data=scaler.transform(X_data)
    return scaled_data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X=data_scaling(x)

In [ ]:
X[0]

array([ 9.7740278 ,  0.02408193,  0.94757366, -0.31879046,  0.        ,
        0.        ,  2.4506679 ,  1.83202993,  0.        ,  2.72239047])

In [ ]:
y[0]

177

In [ ]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# X_scaled = scaler.fit_transform(X)
# X_scaled[0]

In [ ]:
# X_scaled.shape

In [ ]:
# y.shape

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_squared_error
from sklearn import metrics

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **LINEAR REGRESSION**

In [ ]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
predict_train = lin_reg.predict(X_train)
rmse_train = mean_squared_error(y_train,predict_train)**(0.5)
print('RMSE on train dataset : ', rmse_train)

RMSE on train dataset :  345.32003330622234


In [ ]:
predict_test = lin_reg.predict(X_test)
rmse_test = mean_squared_error(y_test,predict_test)**(0.5)
print('RMSE on test dataset : ', rmse_test)

RMSE on test dataset :  339.74973272640955


In [ ]:
print("MSE on test dataset : ", mean_squared_error(y_test, predict_test))

MSE on test dataset :  115429.88088766672


# **DECISION TREES**

In [ ]:
dec_reg = DecisionTreeRegressor(random_state=1)
dec_reg.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [ ]:
pred_dec = dec_reg.predict(X_test)
print("Mean Squared Log Error is ", mean_squared_log_error(y_test, pred_dec))

Mean Squared Log Error is  0.5041017590398493


In [ ]:
print("RMSLE on test dataset : ", mean_squared_log_error(y_test, pred_dec)**(0.5))

RMSLE on test dataset :  0.7100012387593766


In [ ]:
print("RMSE on test dataset : ", mean_squared_error(y_test, pred_dec)**(0.5))

RMSE on test dataset :  227.56325173765575


In [ ]:
print("MSE on test dataset : ", mean_squared_error(y_test, pred_dec))

MSE on test dataset :  51785.03354141568


# **RANDOM FOREST**

In [ ]:
ran_reg = RandomForestRegressor(n_jobs=-1,n_estimators=200,oob_score=True)
ran_reg.fit(X_train, y_train)

KeyboardInterrupt: ignored

In [ ]:
pred_rF = ran_reg.predict(X_test)
print("Mean Squared Log Error is ", mean_squared_log_error(y_test, pred_rF))

In [ ]:
print("RMSLE:", mean_squared_log_error(y_test, pred_rF)**(0.5))

In [ ]:
print("RMSE on test dataset : ", mean_squared_error(y_test, pred_rF)**(0.5))

In [ ]:
metrics.r2_score(y_test, pred_rF)

In [ ]:
import pickle
pickle.dump(ran_reg,open('RandomF_Initial.pkl','wb'))

# **LASSO**

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
l = Lasso() 
l.fit(X_train, y_train) 

In [ ]:
y_pred = l.predict(X_test) 
y_pred[y_pred<0] = 0 

In [ ]:
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

# **KNN**

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
KNN = KNeighborsRegressor()
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)
y_pred[y_pred<0] = 0
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))


In [ ]:
error = []
for i in range(1,100):
  KNN = KNeighborsRegressor(n_neighbors=i)
  KNN.fit(X_train, y_train)
  pred_i = KNN.predict(X_test)
  pred_i[pred_i < 0] = 0
  error.append(100*np.sqrt(metrics.mean_squared_log_error(y_test, pred_i)))


In [ ]:
for i in range(len(error)):
  if error[i] < 58:
    print(error[i])
    print(i)

In [ ]:
plt.figure(figsize=(12,8))
plt.plot(range(1,100),error,color='red',linestyle='dashed',marker='o',markerfacecolor='blue',markersize=10)
plt.title('Error Rate for K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')

In [ ]:
n_neighbours = 5
weights = ['uniform','distance']
algorithm = ['auto', 'ball_tree', 'kd_tree', 'brute']
leaf_size= [30,40,50,60]
p = [1,2,3]

In [ ]:
# Select an algorithm
knn = KNeighborsRegressor()

In [ ]:
# Create 3 folds
from sklearn.model_selection import KFold
seed = 13
kfold = KFold(n_splits=3, shuffle=True, random_state=seed)

In [ ]:
# Define our candidate hyperparameters
hp_candidates = [{'n_neighbors': [4,5,6], 'weights': ['uniform','distance'],'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
'leaf_size' : [30,40,50,60],
'p' : [1,2,3]}]

In [ ]:
# Search for best hyperparameters
grid = GridSearchCV(estimator=algorithm, param_grid=hp_candidates, cv=kfold, scoring='RMSLE')
grid.fit(X, y)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
random_cv = RandomizedSearchCV(estimator=knn,
            param_distributions=hp_candidates,
            cv=5, n_iter=20,
            scoring = 'neg_mean_squared_log_error',n_jobs = 3,
            verbose = 5, 
            return_train_score = True,
            random_state=42)

In [ ]:
random_cv.fit(X_train,y_train)

# **GRADIENT BOOST**

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
GB = GradientBoostingRegressor() 
GB.fit(X_train, y_train) 
y_pred = GB.predict(X_test) 
y_pred[y_pred<0] = 0 
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

# **ELASTICNET**

In [ ]:
from sklearn.linear_model import ElasticNet
EN = ElasticNet() 
EN.fit(X_train, y_train) 
y_pred = EN.predict(X_test) 
y_pred[y_pred<0] = 0  
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

# **ADABOOST**

In [ ]:
from sklearn.ensemble import AdaBoostRegressor
AD = AdaBoostRegressor(random_state=0, n_estimators=100)
AD.fit(X_train, y_train) 
y_pred = AD.predict(X_test) 
y_pred[y_pred<0] = 0  
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

# **RIDGE REGRESSOR**

In [ ]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test) 
y_pred[y_pred<0] = 0  
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

# **CATBOOST**

# **XGB**

In [ ]:
'''
n_estimators = [100, 500, 900, 1000, 1100, 1500]
max_depth = [2, 3, 5, 7, 10, 15]
booster=['gbtree','gblinear']
base_score=[0.25,0.5,0.75,1]
learning_rate=[0.05,0.1,0.13,0.15,0.17,0.20]
min_child_weight=[1,2,3,4,5,9,10]

# Define the grid of hyperparameters to search
hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'learning_rate':learning_rate,
    'min_child_weight':min_child_weight,
    'booster':booster,
    'base_score':base_score
    }
'''    

In [ ]:
 #from sklearn.model_selection import RandomizedSearchCV

In [ ]:
'''
random_cv = RandomizedSearchCV(estimator=XG,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',n_jobs = 4,
            verbose = 5, 
            return_train_score = True,
            random_state=42)
'''

In [ ]:
#random_cv.fit(X_train,y_train)

In [ ]:

#random_cv.best_estimator_

In [ ]:

#random_cv.best_estimator_

In [ ]:
regressor=XGBRegressor(base_score=0.25, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.05, max_delta_step=0,
             max_depth=10, min_child_weight=4, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
regressor.fit(X_train,y_train)

In [ ]:
y_pred = regressor.predict(X_test) 
y_pred[y_pred<0] = 0 
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))