In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# DATA **INTERPRETATION**



In [3]:
train_path = '/content/drive/My Drive/Food_Demand_Forecast_Project/updated_train.csv'
test_path = '/content/drive/My Drive/Food_Demand_Forecast_Project/updated_test.csv'

In [4]:
train_df = pd.read_csv(train_path) 
test_df = pd.read_csv(test_path)

In [5]:
train_df.shape

(456548, 16)

In [6]:
test_df.shape

(32573, 15)

In [7]:
train_df.head()

Unnamed: 0       id  week  center_id  ...  center_type  op_area   category  cuisine
0           0  1379560     1         55  ...       TYPE_C      2.0  Beverages     Thai
1           1  1018704     2         55  ...       TYPE_C      2.0  Beverages     Thai
2           2  1196273     3         55  ...       TYPE_C      2.0  Beverages     Thai
3           3  1116527     4         55  ...       TYPE_C      2.0  Beverages     Thai
4           4  1343872     5         55  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 16 columns]

In [8]:
train_df.category.unique().shape

(14,)

In [9]:
train_df.category.unique()

array(['Beverages', 'Rice Bowl', 'Starters', 'Pasta', 'Sandwich',
       'Biryani', 'Extras', 'Pizza', 'Seafood', 'Other Snacks', 'Desert',
       'Salad', 'Fish', 'Soup'], dtype=object)

In [10]:
train_df.cuisine.unique()

array(['Thai', 'Indian', 'Italian', 'Continental'], dtype=object)

In [11]:
train_df.center_type.unique()

array(['TYPE_C', 'TYPE_B', 'TYPE_A'], dtype=object)

In [12]:
test_df.head()

Unnamed: 0       id  week  center_id  ...  center_type  op_area   category  cuisine
0           0  1028232   146         55  ...       TYPE_C      2.0  Beverages     Thai
1           1  1262649   147         55  ...       TYPE_C      2.0  Beverages     Thai
2           2  1453211   149         55  ...       TYPE_C      2.0  Beverages     Thai
3           3  1262599   150         55  ...       TYPE_C      2.0  Beverages     Thai
4           4  1495848   151         55  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 15 columns]

In [13]:
train_df.drop(['Unnamed: 0'],axis=1,inplace=True)
train_df.head()

id  week  center_id  meal_id  ...  center_type  op_area   category  cuisine
0  1379560     1         55     1885  ...       TYPE_C      2.0  Beverages     Thai
1  1018704     2         55     1885  ...       TYPE_C      2.0  Beverages     Thai
2  1196273     3         55     1885  ...       TYPE_C      2.0  Beverages     Thai
3  1116527     4         55     1885  ...       TYPE_C      2.0  Beverages     Thai
4  1343872     5         55     1885  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 15 columns]

In [14]:
test_df.drop(['Unnamed: 0'],axis=1,inplace=True)
test_df.head()

id  week  center_id  meal_id  ...  center_type  op_area   category  cuisine
0  1028232   146         55     1885  ...       TYPE_C      2.0  Beverages     Thai
1  1262649   147         55     1885  ...       TYPE_C      2.0  Beverages     Thai
2  1453211   149         55     1885  ...       TYPE_C      2.0  Beverages     Thai
3  1262599   150         55     1885  ...       TYPE_C      2.0  Beverages     Thai
4  1495848   151         55     1885  ...       TYPE_C      2.0  Beverages     Thai

[5 rows x 14 columns]

In [15]:
test_df.shape

(32573, 14)

In [16]:
train_df.shape

(456548, 15)

In [17]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32573 entries, 0 to 32572
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     32573 non-null  int64  
 1   week                   32573 non-null  int64  
 2   center_id              32573 non-null  int64  
 3   meal_id                32573 non-null  int64  
 4   checkout_price         32573 non-null  float64
 5   base_price             32573 non-null  float64
 6   emailer_for_promotion  32573 non-null  int64  
 7   homepage_featured      32573 non-null  int64  
 8   city_code              32573 non-null  int64  
 9   region_code            32573 non-null  int64  
 10  center_type            32573 non-null  object 
 11  op_area                32573 non-null  float64
 12  category               32573 non-null  object 
 13  cuisine                32573 non-null  object 
dtypes: float64(3), int64(8), object(3)
memory usage: 3.5+ 

In [18]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   id                     456548 non-null  int64  
 1   week                   456548 non-null  int64  
 2   center_id              456548 non-null  int64  
 3   meal_id                456548 non-null  int64  
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64  
 7   homepage_featured      456548 non-null  int64  
 8   num_orders             456548 non-null  int64  
 9   city_code              456548 non-null  int64  
 10  region_code            456548 non-null  int64  
 11  center_type            456548 non-null  object 
 12  op_area                456548 non-null  float64
 13  category               456548 non-null  object 
 14  cuisine                456548 non-nu

# STATISTICAL **INFO**

In [19]:
train_df.describe()

id           week  ...    region_code        op_area
count  4.565480e+05  456548.000000  ...  456548.000000  456548.000000
mean   1.250096e+06      74.768771  ...      56.614566       4.083590
std    1.443548e+05      41.524956  ...      17.641306       1.091686
min    1.000000e+06       1.000000  ...      23.000000       0.900000
25%    1.124999e+06      39.000000  ...      34.000000       3.600000
50%    1.250184e+06      76.000000  ...      56.000000       4.000000
75%    1.375140e+06     111.000000  ...      77.000000       4.500000
max    1.499999e+06     145.000000  ...      93.000000       7.000000

[8 rows x 12 columns]

# CHECKING FOR NULL **VALUES**

In [20]:
train_df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [21]:
test_df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

# **LABEL ENCODING**

In [22]:
train_df.head(7)

id  week  center_id  meal_id  ...  center_type  op_area   category  cuisine
0  1379560     1         55     1885  ...       TYPE_C      2.0  Beverages     Thai
1  1018704     2         55     1885  ...       TYPE_C      2.0  Beverages     Thai
2  1196273     3         55     1885  ...       TYPE_C      2.0  Beverages     Thai
3  1116527     4         55     1885  ...       TYPE_C      2.0  Beverages     Thai
4  1343872     5         55     1885  ...       TYPE_C      2.0  Beverages     Thai
5  1493612     6         55     1885  ...       TYPE_C      2.0  Beverages     Thai
6  1110832     7         55     1885  ...       TYPE_C      2.0  Beverages     Thai

[7 rows x 15 columns]

In [23]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
train_df["cent_type"] = encoder.fit_transform(train_df["center_type"])
train_df[["center_type", "cent_type"]].head(10)

center_type  cent_type
0      TYPE_C          2
1      TYPE_C          2
2      TYPE_C          2
3      TYPE_C          2
4      TYPE_C          2
5      TYPE_C          2
6      TYPE_C          2
7      TYPE_C          2
8      TYPE_C          2
9      TYPE_C          2

In [24]:
train_df["cent_type"].unique()

array([2, 1, 0])

In [25]:
train_df["categories"] = encoder.fit_transform(train_df["category"])
train_df[["category", "categories"]].head(10)

category  categories
0  Beverages           0
1  Beverages           0
2  Beverages           0
3  Beverages           0
4  Beverages           0
5  Beverages           0
6  Beverages           0
7  Beverages           0
8  Beverages           0
9  Beverages           0

In [26]:
train_df["categories"].unique()

array([ 0,  8, 13,  6, 10,  1,  3,  7, 11,  5,  2,  9,  4, 12])

In [27]:
train_df["Cuisine"] = encoder.fit_transform(train_df["cuisine"])
train_df[["cuisine", "Cuisine"]].head(10)

cuisine  Cuisine
0    Thai        3
1    Thai        3
2    Thai        3
3    Thai        3
4    Thai        3
5    Thai        3
6    Thai        3
7    Thai        3
8    Thai        3
9    Thai        3

In [28]:
train_df["Cuisine"].unique()

array([3, 1, 2, 0])

In [29]:
train_df_enc = train_df.drop(['center_type','category','cuisine'], axis=1)

In [30]:
train_df_enc.head()

id  week  center_id  meal_id  ...  op_area  cent_type  categories  Cuisine
0  1379560     1         55     1885  ...      2.0          2           0        3
1  1018704     2         55     1885  ...      2.0          2           0        3
2  1196273     3         55     1885  ...      2.0          2           0        3
3  1116527     4         55     1885  ...      2.0          2           0        3
4  1343872     5         55     1885  ...      2.0          2           0        3

[5 rows x 15 columns]

# **FEATURE EXTRACTION**

In [38]:
x = train_df_enc.drop(['num_orders'],axis=1)

In [39]:
y = train_df_enc['num_orders']

In [40]:
add_sub_price=x["checkout_price"]-x["base_price"]

In [41]:
add_sub_price=add_sub_price.to_frame()
add_sub_price.columns=['change_in_price_during_checkout']

In [42]:
features=['city_code','week', 'base_price', 'checkout_price','emailer_for_promotion', 'homepage_featured', 'cent_type', 'op_area', 'categories',
       'Cuisine']

In [43]:
x = x[features]

In [44]:
x.head()

city_code  week  base_price  ...  op_area  categories  Cuisine
0        647     1      152.29  ...      2.0           0        3
1        647     2      152.29  ...      2.0           0        3
2        647     3      133.92  ...      2.0           0        3
3        647     4      134.86  ...      2.0           0        3
4        647     5      147.50  ...      2.0           0        3

[5 rows x 10 columns]

In [88]:
x['op_area'].unique()

array([2. , 3.6, 3.7, 5.3, 3.8, 6.7, 5.6, 3.9, 3.4, 5. , 2.8, 2.4, 4.8,
       4. , 4.6, 4.4, 4.5, 4.1, 0.9, 4.2, 2.9, 2.7, 4.7, 3.2, 3. , 7. ,
       1.9, 3.5, 6.3, 5.1])

In [89]:
x['city_code'].unique()

array([647, 614, 679, 659, 526, 590, 599, 685, 461, 649, 541, 478, 703,
       576, 628, 702, 579, 596, 648, 632, 522, 615, 577, 517, 651, 683,
       713, 609, 675, 553, 593, 654, 693, 658, 515, 556, 561, 680, 620,
       638, 700, 676, 604, 456, 562, 695, 699, 602, 485, 698, 473])

# **SCALING THE VALUES**

In [45]:
def data_scaling(X_data):
    scaler=StandardScaler(with_mean=False)
    scaler.fit(X_data)
    scaled_data=scaler.transform(X_data)
    return scaled_data

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
X=data_scaling(x)

In [48]:
X[0]

array([9.7740278 , 0.02408193, 0.94757366, 0.89466717, 0.        ,
       0.        , 2.4506679 , 1.83202993, 0.        , 2.72239047])

In [49]:
y[0]

177

In [50]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# X_scaled = scaler.fit_transform(X)
# X_scaled[0]

In [51]:
# X_scaled.shape

In [52]:
# y.shape

In [53]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_squared_error
from sklearn import metrics

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# **LINEAR REGRESSION**

In [55]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [56]:
predict_train = lin_reg.predict(X_train)
predict_train[predict_train<0] = 0
rmse_train = mean_squared_error(y_train,predict_train)**(0.5)
print('RMSE on train dataset : ', rmse_train)

RMSE on train dataset :  344.01639924175504


In [57]:
predict_test = lin_reg.predict(X_test)
rmse_test = mean_squared_error(y_test,predict_test)**(0.5)
print('RMSE on test dataset : ', rmse_test)

RMSE on test dataset :  339.7497327264086


In [58]:
print("MSE on test dataset : ", mean_squared_error(y_test, predict_test))

MSE on test dataset :  115429.88088766605


In [59]:
predict_test[predict_test<0] = 0
print("RMSLE on test dataset : ", mean_squared_log_error(y_test, predict_test)**(0.5))

RMSLE on test dataset :  1.5621298437415496


# **DECISION TREES**

In [60]:
dec_reg = DecisionTreeRegressor(random_state=1)
dec_reg.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [61]:
pred_dec = dec_reg.predict(X_test)
print("Mean Squared Log Error is ", mean_squared_log_error(y_test, pred_dec))

Mean Squared Log Error is  0.5015627751808317


In [62]:
print("RMSLE on test dataset : ", mean_squared_log_error(y_test, pred_dec)**(0.5))

RMSLE on test dataset :  0.7082109679896462


In [63]:
print("RMSE on test dataset : ", mean_squared_error(y_test, pred_dec)**(0.5))

RMSE on test dataset :  236.8148667094672


In [64]:
print("MSE on test dataset : ", mean_squared_error(y_test, pred_dec))

MSE on test dataset :  56081.28109462271


# **RANDOM FOREST**

In [65]:
ran_reg = RandomForestRegressor(n_jobs=-1,n_estimators=200,oob_score=True)
ran_reg.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=-1, oob_score=True,
                      random_state=None, verbose=0, warm_start=False)

In [66]:
pred_rF = ran_reg.predict(X_test)
print("Mean Squared Log Error is ", mean_squared_log_error(y_test, pred_rF))

Mean Squared Log Error is  0.3008121325738194


In [67]:
print("RMSLE:", mean_squared_log_error(y_test, pred_rF)**(0.5))

RMSLE: 0.5484634286566602


In [68]:
print("RMSE on test dataset : ", mean_squared_error(y_test, pred_rF)**(0.5))

RMSE on test dataset :  170.26146428916104


In [69]:
metrics.r2_score(y_test, pred_rF)

0.8093326166139484

In [70]:
import pickle
pickle.dump(ran_reg,open('RandomF_Initial.pkl','wb'))

# **LASSO**

In [71]:
from sklearn.linear_model import Lasso

In [72]:
l = Lasso() 
l.fit(X_train, y_train) 

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [73]:
y_pred = l.predict(X_test) 
y_pred[y_pred<0] = 0 

In [74]:
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 154.20649647342228


# **KNN**

In [75]:
from sklearn.neighbors import KNeighborsRegressor
KNN = KNeighborsRegressor()
KNN.fit(X_train, y_train)
y_pred = KNN.predict(X_test)
y_pred[y_pred<0] = 0
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))


RMSLE: 57.43638142999695


# **GRADIENT BOOST**

In [76]:
from sklearn.ensemble import GradientBoostingRegressor
GB = GradientBoostingRegressor() 
GB.fit(X_train, y_train) 
y_pred = GB.predict(X_test) 
y_pred[y_pred<0] = 0 
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 100.10254583280994


# **ELASTICNET**

In [77]:
from sklearn.linear_model import ElasticNet
EN = ElasticNet() 
EN.fit(X_train, y_train) 
y_pred = EN.predict(X_test) 
y_pred[y_pred<0] = 0  
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 124.62315423636801


# **ADABOOST**

In [78]:
from sklearn.ensemble import AdaBoostRegressor
AD = AdaBoostRegressor(random_state=0, n_estimators=100)
AD.fit(X_train, y_train) 
y_pred = AD.predict(X_test) 
y_pred[y_pred<0] = 0  
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 259.40916826003985


# **RIDGE REGRESSOR**

In [79]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test) 
y_pred[y_pred<0] = 0  
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 156.21246192825225


# **CATBOOST**

# **XGB**

In [80]:
from xgboost import XGBRegressor
regressor=XGBRegressor(base_score=0.25, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.05, max_delta_step=0,
             max_depth=10, min_child_weight=4, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [81]:
regressor.fit(X_train,y_train)

[06:10:48] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.25, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.05, max_delta_step=0,
             max_depth=10, min_child_weight=4, missing=None, n_estimators=1000,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [82]:
y_pred = regressor.predict(X_test) 
y_pred[y_pred<0] = 0 
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 57.958938900467224


In [83]:
def evaluate(y_test, y_pred):
    return 100 * np.sqrt(mean_squared_error(y_test, y_pred))

In [84]:
evaluate(y_test, regressor.predict(X_test))

15030.351029175476

In [85]:
xgb = XGBRegressor(objective='reg:squarederror', random_state=41,missing=0.0, n_jobs=8, 
                   max_depth=9, n_estimators=300, min_child_weight=45)
xgb.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=9, min_child_weight=45, missing=0.0, n_estimators=300,
             n_jobs=8, nthread=None, objective='reg:squarederror',
             random_state=41, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [86]:
y_pred = xgb.predict(X_test) 
y_pred[y_pred<0] = 0 
print('RMSLE:', 100*np.sqrt(metrics.mean_squared_log_error(y_test, y_pred)))

RMSLE: 63.056515374426056


In [87]:
evaluate(y_test, xgb.predict(X_test))

16184.450492470332