In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# DATA **INTERPRETATION**



In [2]:
train_path = 'updated_train.csv'
test_path = 'updated_test.csv'

In [3]:
train_df = pd.read_csv(train_path) 
test_df = pd.read_csv(test_path)

In [4]:
train_df.shape

(456548, 16)

In [5]:
test_df.shape

(32573, 15)

In [6]:
train_df.head()

Unnamed: 0       id  week  center_id  meal_id  checkout_price  base_price  \
0           0  1379560     1         55     1885          136.83      152.29   
1           1  1018704     2         55     1885          135.83      152.29   
2           2  1196273     3         55     1885          132.92      133.92   
3           3  1116527     4         55     1885          135.86      134.86   
4           4  1343872     5         55     1885          146.50      147.50   

   emailer_for_promotion  homepage_featured  num_orders  city_code  \
0                      0                  0         177        647   
1                      0                  0         323        647   
2                      0                  0          96        647   
3                      0                  0         163        647   
4                      0                  0         215        647   

   region_code center_type  op_area   category cuisine  
0           56      TYPE_C      2.0  Beverages    Thai  
1           56      TYPE_C      2.0  Beverages    Thai  
2           56      TYPE_C      2.0  Beverages    Thai  
3           56      TYPE_C      2.0  Beverages    Thai  
4           56      TYPE_C      2.0  Beverages    Thai

In [7]:
train_df.category.unique().shape

(14,)

In [8]:
train_df.category.unique()

array(['Beverages', 'Rice Bowl', 'Starters', 'Pasta', 'Sandwich',
       'Biryani', 'Extras', 'Pizza', 'Seafood', 'Other Snacks', 'Desert',
       'Salad', 'Fish', 'Soup'], dtype=object)

In [9]:
train_df.cuisine.unique()

array(['Thai', 'Indian', 'Italian', 'Continental'], dtype=object)

In [10]:
train_df.center_type.unique()

array(['TYPE_C', 'TYPE_B', 'TYPE_A'], dtype=object)

In [11]:
test_df.head()

Unnamed: 0       id  week  center_id  meal_id  checkout_price  base_price  \
0           0  1028232   146         55     1885          158.11      159.11   
1           1  1262649   147         55     1885          159.11      159.11   
2           2  1453211   149         55     1885          157.14      158.14   
3           3  1262599   150         55     1885          159.14      157.14   
4           4  1495848   151         55     1885          160.11      159.11   

   emailer_for_promotion  homepage_featured  city_code  region_code  \
0                      0                  0        647           56   
1                      0                  0        647           56   
2                      0                  0        647           56   
3                      0                  0        647           56   
4                      0                  0        647           56   

  center_type  op_area   category cuisine  
0      TYPE_C      2.0  Beverages    Thai  
1      TYPE_C      2.0  Beverages    Thai  
2      TYPE_C      2.0  Beverages    Thai  
3      TYPE_C      2.0  Beverages    Thai  
4      TYPE_C      2.0  Beverages    Thai

In [12]:
train_df.drop(['Unnamed: 0'],axis=1,inplace=True)
train_df.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1018704     2         55     1885          135.83      152.29   
2  1196273     3         55     1885          132.92      133.92   
3  1116527     4         55     1885          135.86      134.86   
4  1343872     5         55     1885          146.50      147.50   

   emailer_for_promotion  homepage_featured  num_orders  city_code  \
0                      0                  0         177        647   
1                      0                  0         323        647   
2                      0                  0          96        647   
3                      0                  0         163        647   
4                      0                  0         215        647   

   region_code center_type  op_area   category cuisine  
0           56      TYPE_C      2.0  Beverages    Thai  
1           56      TYPE_C      2.0  Beverages    Thai  
2           56      TYPE_C      2.0  Beverages    Thai  
3           56      TYPE_C      2.0  Beverages    Thai  
4           56      TYPE_C      2.0  Beverages    Thai

In [13]:
test_df.drop(['Unnamed: 0'],axis=1,inplace=True)
test_df.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1028232   146         55     1885          158.11      159.11   
1  1262649   147         55     1885          159.11      159.11   
2  1453211   149         55     1885          157.14      158.14   
3  1262599   150         55     1885          159.14      157.14   
4  1495848   151         55     1885          160.11      159.11   

   emailer_for_promotion  homepage_featured  city_code  region_code  \
0                      0                  0        647           56   
1                      0                  0        647           56   
2                      0                  0        647           56   
3                      0                  0        647           56   
4                      0                  0        647           56   

  center_type  op_area   category cuisine  
0      TYPE_C      2.0  Beverages    Thai  
1      TYPE_C      2.0  Beverages    Thai  
2      TYPE_C      2.0  Beverages    Thai  
3      TYPE_C      2.0  Beverages    Thai  
4      TYPE_C      2.0  Beverages    Thai

In [14]:
test_df.shape

(32573, 14)

In [15]:
train_df.shape

(456548, 15)

In [16]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32573 entries, 0 to 32572
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     32573 non-null  int64  
 1   week                   32573 non-null  int64  
 2   center_id              32573 non-null  int64  
 3   meal_id                32573 non-null  int64  
 4   checkout_price         32573 non-null  float64
 5   base_price             32573 non-null  float64
 6   emailer_for_promotion  32573 non-null  int64  
 7   homepage_featured      32573 non-null  int64  
 8   city_code              32573 non-null  int64  
 9   region_code            32573 non-null  int64  
 10  center_type            32573 non-null  object 
 11  op_area                32573 non-null  float64
 12  category               32573 non-null  object 
 13  cuisine                32573 non-null  object 
dtypes: float64(3), int64(8), object(3)
memory usage: 3.5+ 

In [17]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456548 entries, 0 to 456547
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   id                     456548 non-null  int64  
 1   week                   456548 non-null  int64  
 2   center_id              456548 non-null  int64  
 3   meal_id                456548 non-null  int64  
 4   checkout_price         456548 non-null  float64
 5   base_price             456548 non-null  float64
 6   emailer_for_promotion  456548 non-null  int64  
 7   homepage_featured      456548 non-null  int64  
 8   num_orders             456548 non-null  int64  
 9   city_code              456548 non-null  int64  
 10  region_code            456548 non-null  int64  
 11  center_type            456548 non-null  object 
 12  op_area                456548 non-null  float64
 13  category               456548 non-null  object 
 14  cuisine                456548 non-nu

# STATISTICAL **INFO**

In [18]:
train_df.describe()

id           week      center_id        meal_id  \
count  4.565480e+05  456548.000000  456548.000000  456548.000000   
mean   1.250096e+06      74.768771      82.105796    2024.337458   
std    1.443548e+05      41.524956      45.975046     547.420920   
min    1.000000e+06       1.000000      10.000000    1062.000000   
25%    1.124999e+06      39.000000      43.000000    1558.000000   
50%    1.250184e+06      76.000000      76.000000    1993.000000   
75%    1.375140e+06     111.000000     110.000000    2539.000000   
max    1.499999e+06     145.000000     186.000000    2956.000000   

       checkout_price     base_price  emailer_for_promotion  \
count   456548.000000  456548.000000          456548.000000   
mean       332.238933     354.156627               0.081152   
std        152.939723     160.715914               0.273069   
min          2.970000      55.350000               0.000000   
25%        228.950000     243.500000               0.000000   
50%        296.820000     310.460000               0.000000   
75%        445.230000     458.870000               0.000000   
max        866.270000     866.270000               1.000000   

       homepage_featured     num_orders      city_code    region_code  \
count       456548.00000  456548.000000  456548.000000  456548.000000   
mean             0.10920     261.872760     601.553399      56.614566   
std              0.31189     395.922798      66.195914      17.641306   
min              0.00000      13.000000     456.000000      23.000000   
25%              0.00000      54.000000     553.000000      34.000000   
50%              0.00000     136.000000     596.000000      56.000000   
75%              0.00000     324.000000     651.000000      77.000000   
max              1.00000   24299.000000     713.000000      93.000000   

             op_area  
count  456548.000000  
mean        4.083590  
std         1.091686  
min         0.900000  
25%         3.600000  
50%         4.000000  
75%         4.500000  
max         7.000000

# CHECKING FOR NULL **VALUES**

In [19]:
train_df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

In [20]:
test_df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
city_code                0
region_code              0
center_type              0
op_area                  0
category                 0
cuisine                  0
dtype: int64

# **LABEL ENCODING**

In [21]:
train_df.head(7)

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1018704     2         55     1885          135.83      152.29   
2  1196273     3         55     1885          132.92      133.92   
3  1116527     4         55     1885          135.86      134.86   
4  1343872     5         55     1885          146.50      147.50   
5  1493612     6         55     1885          146.53      146.53   
6  1110832     7         55     1885          145.53      146.53   

   emailer_for_promotion  homepage_featured  num_orders  city_code  \
0                      0                  0         177        647   
1                      0                  0         323        647   
2                      0                  0          96        647   
3                      0                  0         163        647   
4                      0                  0         215        647   
5                      0                  0         285        647   
6                      0                  0         148        647   

   region_code center_type  op_area   category cuisine  
0           56      TYPE_C      2.0  Beverages    Thai  
1           56      TYPE_C      2.0  Beverages    Thai  
2           56      TYPE_C      2.0  Beverages    Thai  
3           56      TYPE_C      2.0  Beverages    Thai  
4           56      TYPE_C      2.0  Beverages    Thai  
5           56      TYPE_C      2.0  Beverages    Thai  
6           56      TYPE_C      2.0  Beverages    Thai

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
train_df["cent_type"] = encoder.fit_transform(train_df["center_type"])
train_df[["center_type", "cent_type"]].head(10)

center_type  cent_type
0      TYPE_C          2
1      TYPE_C          2
2      TYPE_C          2
3      TYPE_C          2
4      TYPE_C          2
5      TYPE_C          2
6      TYPE_C          2
7      TYPE_C          2
8      TYPE_C          2
9      TYPE_C          2

In [23]:
train_df["cent_type"].unique()

array([2, 1, 0])

In [24]:
train_df["categories"] = encoder.fit_transform(train_df["category"])
train_df[["category", "categories"]].head(10)

category  categories
0  Beverages           0
1  Beverages           0
2  Beverages           0
3  Beverages           0
4  Beverages           0
5  Beverages           0
6  Beverages           0
7  Beverages           0
8  Beverages           0
9  Beverages           0

In [25]:
train_df[train_df['categories']==2]['category']

318663    Desert
318664    Desert
318665    Desert
318666    Desert
318667    Desert
           ...  
347952    Desert
347953    Desert
347954    Desert
347955    Desert
347956    Desert
Name: category, Length: 29294, dtype: object

In [26]:
train_df["categories"].unique()

array([ 0,  8, 13,  6, 10,  1,  3,  7, 11,  5,  2,  9,  4, 12])

In [27]:
train_df["Cuisine"] = encoder.fit_transform(train_df["cuisine"])
train_df[["cuisine", "Cuisine"]].tail(37000)

cuisine  Cuisine
419548         Thai        3
419549         Thai        3
419550         Thai        3
419551         Thai        3
419552         Thai        3
...             ...      ...
456543  Continental        0
456544  Continental        0
456545  Continental        0
456546  Continental        0
456547  Continental        0

[37000 rows x 2 columns]

In [28]:
train_df["Cuisine"].unique()

array([3, 1, 2, 0])

In [29]:
train_df_enc = train_df.drop(['center_type','category','cuisine'], axis=1)

In [30]:
train_df_enc.head()

id  week  center_id  meal_id  checkout_price  base_price  \
0  1379560     1         55     1885          136.83      152.29   
1  1018704     2         55     1885          135.83      152.29   
2  1196273     3         55     1885          132.92      133.92   
3  1116527     4         55     1885          135.86      134.86   
4  1343872     5         55     1885          146.50      147.50   

   emailer_for_promotion  homepage_featured  num_orders  city_code  \
0                      0                  0         177        647   
1                      0                  0         323        647   
2                      0                  0          96        647   
3                      0                  0         163        647   
4                      0                  0         215        647   

   region_code  op_area  cent_type  categories  Cuisine  
0           56      2.0          2           0        3  
1           56      2.0          2           0        3  
2           56      2.0          2           0        3  
3           56      2.0          2           0        3  
4           56      2.0          2           0        3

# **FEATURE EXTRACTION**

In [31]:
x = train_df_enc.drop(['num_orders'],axis=1)

In [32]:
y = train_df_enc['num_orders']

In [33]:
add_sub_price=x["checkout_price"]-x["base_price"]

In [34]:
add_sub_price=add_sub_price.to_frame()
add_sub_price.columns=['change_in_price_during_checkout']

In [35]:
x=pd.concat([x,add_sub_price],axis=1).drop(["checkout_price"],axis=1)

In [36]:
features=['homepage_featured','emailer_for_promotion',  'op_area','Cuisine','city_code','region_code',
       'categories']

In [37]:
x = x[features]

In [38]:
x.head()

homepage_featured  emailer_for_promotion  op_area  Cuisine  city_code  \
0                  0                      0      2.0        3        647   
1                  0                      0      2.0        3        647   
2                  0                      0      2.0        3        647   
3                  0                      0      2.0        3        647   
4                  0                      0      2.0        3        647   

   region_code  categories  
0           56           0  
1           56           0  
2           56           0  
3           56           0  
4           56           0

# **SCALING THE VALUES**

In [39]:
def data_scaling(X_data):
    scaler=StandardScaler(with_mean=False)
    scaler.fit(X_data)
    scaled_data=scaler.transform(X_data)
    return scaled_data

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
X=data_scaling(x)

In [42]:
X[0]

array([0.        , 0.        , 1.83202993, 2.72239047, 9.7740278 ,
       3.17437171, 0.        ])

In [43]:
y[0]

177

In [44]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# X_scaled = scaler.fit_transform(X)
# X_scaled[0]

In [45]:
# X_scaled.shape

In [46]:
# y.shape

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_squared_error
from sklearn import metrics

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:
ran_reg = RandomForestRegressor(random_state=0)
ran_reg.fit(X_train, y_train)

RandomForestRegressor(random_state=0)

In [50]:
pred_rF = ran_reg.predict(X_test)
print("Mean Squared Log Error is ", mean_squared_log_error(y_test, pred_rF))

Mean Squared Log Error is  0.3949110897953502


In [51]:
print("RMSLE:", mean_squared_log_error(y_test, pred_rF)**(0.5))

RMSLE: 0.6284195173571157


In [52]:
metrics.r2_score(y_test, pred_rF)

0.6514016688296089

In [53]:
import pickle
pickle.dump(ran_reg,open('rf.pkl','wb'))